version: '3.8'

services:
  robot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .dev.env
    volumes:
      - ./procedure_tools:/opt/robotframework/procedure_tools
      - ./robot_tests:/opt/robotframework/tests
      - ./reports:/opt/robotframework/reports
