"""
What each procedure may put in its config, by procedure and key.

``options`` is what the key may be set to and ``default`` is what it is without
being set. A key with one option is pinned by the schema: the API refuses any
other value, so the only thing to test about it is that refusal. A key with
several is a real branch of behaviour, and the same key can be pinned in one
procedure and free in another.

Generated by ``generate_config_schemas.py`` from the standards library
at 1.0.218-130-g5b78d18. Regenerate it against the standards version the environment under
test runs; a different branch can pin different values.
"""

from typing import Any

SCHEMAS: dict[str, dict[str, dict[str, Any]]] = {
    "TenderConfig/aboveThreshold": {
        "awardComplainDuration": {
            "options": [5],
            "default": 5,
            "minimum": 5,
            "maximum": 5,
        },
        "cancellationComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "enquiryPeriodRegulation": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "hasAuction": {
            "options": [True, False],
            "default": True,
        },
        "hasAwardComplaints": {
            "options": [True],
            "default": True,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [True],
            "default": True,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True, False],
            "default": True,
        },
        "minBidsNumber": {
            "options": [1],
            "default": 1,
            "minimum": 1,
            "maximum": 1,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [7],
            "default": 7,
            "minimum": 7,
            "maximum": 7,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/aboveThresholdEU": {
        "awardComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "cancellationComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "enquiryPeriodRegulation": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "hasAuction": {
            "options": [True, False],
            "default": True,
        },
        "hasAwardComplaints": {
            "options": [True],
            "default": True,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [True],
            "default": True,
        },
        "hasQualificationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasTenderComplaints": {
            "options": [True],
            "default": True,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [2],
            "default": 2,
            "minimum": 2,
            "maximum": 2,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [30],
            "default": 30,
            "minimum": 30,
            "maximum": 30,
        },
        "qualificationComplainDuration": {
            "options": [5],
            "default": 5,
            "minimum": 5,
            "maximum": 5,
        },
        "qualificationDuration": {
            "options": [20],
            "default": 20,
            "minimum": 20,
            "maximum": 20,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [4],
            "default": 4,
            "minimum": 4,
            "maximum": 4,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/aboveThresholdUA.defense": {
        "awardComplainDuration": {
            "options": [4],
            "default": 4,
            "minimum": 4,
            "maximum": 4,
        },
        "cancellationComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "enquiryPeriodRegulation": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "hasAuction": {
            "options": [True, False],
            "default": True,
        },
        "hasAwardComplaints": {
            "options": [True],
            "default": True,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [True],
            "default": True,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [1],
            "default": 1,
            "minimum": 1,
            "maximum": 1,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [6],
            "default": 6,
            "minimum": 6,
            "maximum": 6,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [2],
            "default": 2,
            "minimum": 2,
            "maximum": 2,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/aboveThresholdUA": {
        "awardComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "cancellationComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "enquiryPeriodRegulation": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "hasAuction": {
            "options": [True, False],
            "default": True,
        },
        "hasAwardComplaints": {
            "options": [True],
            "default": True,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [True],
            "default": True,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [2],
            "default": 2,
            "minimum": 2,
            "maximum": 2,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [15],
            "default": 15,
            "minimum": 15,
            "maximum": 15,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [4],
            "default": 4,
            "minimum": 4,
            "maximum": 4,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/belowThreshold": {
        "awardComplainDuration": {
            "options": [2],
            "default": 2,
            "minimum": 2,
            "maximum": 2,
        },
        "cancellationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "clarificationUntilDuration": {
            "options": [1],
            "default": 1,
            "minimum": 1,
            "maximum": 1,
        },
        "enquiryPeriodRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "hasAuction": {
            "options": [True, False],
            "default": True,
        },
        "hasAwardComplaints": {
            "options": [False],
            "default": False,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasEnquiries": {
            "options": [True],
            "default": True,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [False],
            "default": False,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True, False],
            "default": True,
        },
        "minBidsNumber": {
            "options": [1],
            "default": 1,
            "minimum": 1,
            "maximum": 1,
        },
        "minEnquiriesDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "minTenderingDuration": {
            "options": [2],
            "default": 2,
            "minimum": 2,
            "maximum": 2,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/closeFrameworkAgreementSelectionUA": {
        "awardComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "cancellationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "clarificationUntilDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "enquiryPeriodRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "hasAuction": {
            "options": [True],
            "default": True,
        },
        "hasAwardComplaints": {
            "options": [False],
            "default": False,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasEnquiries": {
            "options": [True],
            "default": True,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [True],
            "default": True,
        },
        "hasPrequalification": {
            "options": [False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [False],
            "default": False,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [1],
            "default": 1,
            "minimum": 1,
            "maximum": 1,
        },
        "minEnquiriesDuration": {
            "options": [1],
            "default": 1,
            "minimum": 1,
            "maximum": 1,
        },
        "minTenderingDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/closeFrameworkAgreementUA": {
        "awardComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "cancellationComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "enquiryPeriodRegulation": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "hasAuction": {
            "options": [True],
            "default": True,
        },
        "hasAwardComplaints": {
            "options": [True],
            "default": True,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [True],
            "default": True,
        },
        "hasQualificationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasTenderComplaints": {
            "options": [True],
            "default": True,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [30],
            "default": 30,
            "minimum": 30,
            "maximum": 30,
        },
        "qualificationComplainDuration": {
            "options": [5],
            "default": 5,
            "minimum": 5,
            "maximum": 5,
        },
        "qualificationDuration": {
            "options": [20],
            "default": 20,
            "minimum": 20,
            "maximum": 20,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [4],
            "default": 4,
            "minimum": 4,
            "maximum": 4,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/competitiveDialogueEU": {
        "awardComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "cancellationComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "enquiryPeriodRegulation": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "hasAuction": {
            "options": [False],
            "default": False,
        },
        "hasAwardComplaints": {
            "options": [False],
            "default": False,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [True],
            "default": True,
        },
        "hasQualificationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasTenderComplaints": {
            "options": [True],
            "default": True,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [30],
            "default": 30,
            "minimum": 30,
            "maximum": 30,
        },
        "qualificationComplainDuration": {
            "options": [5],
            "default": 5,
            "minimum": 5,
            "maximum": 5,
        },
        "qualificationDuration": {
            "options": [20],
            "default": 20,
            "minimum": 20,
            "maximum": 20,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [4],
            "default": 4,
            "minimum": 4,
            "maximum": 4,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/competitiveDialogueEU.stage2": {
        "awardComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "cancellationComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "enquiryPeriodRegulation": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "hasAuction": {
            "options": [True],
            "default": True,
        },
        "hasAwardComplaints": {
            "options": [True],
            "default": True,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [True],
            "default": True,
        },
        "hasQualificationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasTenderComplaints": {
            "options": [True],
            "default": True,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [2],
            "default": 2,
            "minimum": 2,
            "maximum": 2,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [30],
            "default": 30,
            "minimum": 30,
            "maximum": 30,
        },
        "qualificationComplainDuration": {
            "options": [5],
            "default": 5,
            "minimum": 5,
            "maximum": 5,
        },
        "qualificationDuration": {
            "options": [20],
            "default": 20,
            "minimum": 20,
            "maximum": 20,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [4],
            "default": 4,
            "minimum": 4,
            "maximum": 4,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/competitiveDialogueUA": {
        "awardComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "cancellationComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "enquiryPeriodRegulation": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "hasAuction": {
            "options": [False],
            "default": False,
        },
        "hasAwardComplaints": {
            "options": [False],
            "default": False,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [True],
            "default": True,
        },
        "hasQualificationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasTenderComplaints": {
            "options": [True],
            "default": True,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [30],
            "default": 30,
            "minimum": 30,
            "maximum": 30,
        },
        "qualificationComplainDuration": {
            "options": [5],
            "default": 5,
            "minimum": 5,
            "maximum": 5,
        },
        "qualificationDuration": {
            "options": [20],
            "default": 20,
            "minimum": 20,
            "maximum": 20,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [4],
            "default": 4,
            "minimum": 4,
            "maximum": 4,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/competitiveDialogueUA.stage2": {
        "awardComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "cancellationComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "enquiryPeriodRegulation": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "hasAuction": {
            "options": [True],
            "default": True,
        },
        "hasAwardComplaints": {
            "options": [True],
            "default": True,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [True],
            "default": True,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [2],
            "default": 2,
            "minimum": 2,
            "maximum": 2,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [15],
            "default": 15,
            "minimum": 15,
            "maximum": 15,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [4],
            "default": 4,
            "minimum": 4,
            "maximum": 4,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/competitiveOrdering": {
        "awardComplainDuration": {
            "options": [5],
            "default": 5,
            "minimum": 5,
            "maximum": 5,
        },
        "cancellationComplainDuration": {
            "options": [0, 10],
            "default": 0,
        },
        "clarificationUntilDuration": {
            "options": [0, 3],
            "default": 0,
        },
        "enquiryPeriodRegulation": {
            "options": [3, 0],
            "default": 3,
        },
        "hasAuction": {
            "options": [True, False],
            "default": True,
        },
        "hasAwardComplaints": {
            "options": [False, True],
            "default": False,
        },
        "hasAwardingOrder": {
            "options": [True, False],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [False, True],
            "default": False,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [True, False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [True],
            "default": True,
        },
        "hasPrequalification": {
            "options": [False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [False, True],
            "default": False,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True, False],
            "default": False,
        },
        "minBidsNumber": {
            "options": [1],
            "default": 1,
            "minimum": 1,
            "maximum": 1,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [2, 7],
            "default": 7,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restricted": {
            "options": [False, True],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [0, 3],
            "default": 0,
        },
        "valueCurrencyEquality": {
            "options": [True, False],
            "default": True,
        },
    },
    "TenderConfig/competitiveOrdering.long": {
        "awardComplainDuration": {
            "options": [5],
            "default": 5,
            "minimum": 5,
            "maximum": 5,
        },
        "cancellationComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "enquiryPeriodRegulation": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "hasAuction": {
            "options": [True, False],
            "default": True,
        },
        "hasAwardComplaints": {
            "options": [True],
            "default": True,
        },
        "hasAwardingOrder": {
            "options": [True, False],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [True, False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [True],
            "default": True,
        },
        "hasPrequalification": {
            "options": [False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [True],
            "default": True,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True, False],
            "default": False,
        },
        "minBidsNumber": {
            "options": [1],
            "default": 1,
            "minimum": 1,
            "maximum": 1,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [7],
            "default": 7,
            "minimum": 7,
            "maximum": 7,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restricted": {
            "options": [False, True],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "valueCurrencyEquality": {
            "options": [True, False],
            "default": True,
        },
    },
    "TenderConfig/competitiveOrdering.short": {
        "awardComplainDuration": {
            "options": [5],
            "default": 5,
            "minimum": 5,
            "maximum": 5,
        },
        "cancellationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "clarificationUntilDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "enquiryPeriodRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "hasAuction": {
            "options": [True, False],
            "default": False,
        },
        "hasAwardComplaints": {
            "options": [False],
            "default": False,
        },
        "hasAwardingOrder": {
            "options": [True, False],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [True, False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [True],
            "default": True,
        },
        "hasPrequalification": {
            "options": [False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [False],
            "default": False,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True, False],
            "default": False,
        },
        "minBidsNumber": {
            "options": [1],
            "default": 1,
            "minimum": 1,
            "maximum": 1,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [2],
            "default": 2,
            "minimum": 2,
            "maximum": 2,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restricted": {
            "options": [False, True],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "valueCurrencyEquality": {
            "options": [True, False],
            "default": True,
        },
    },
    "TenderConfig/complexAsset.arma": {
        "awardComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "cancellationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "clarificationUntilDuration": {
            "options": [5],
            "default": 5,
            "minimum": 5,
            "maximum": 5,
        },
        "enquiryPeriodRegulation": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "hasAuction": {
            "options": [True],
            "default": True,
        },
        "hasAwardComplaints": {
            "options": [False],
            "default": False,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [True],
            "default": True,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [False],
            "default": False,
        },
        "hasValueEstimation": {
            "options": [False],
            "default": False,
        },
        "hasValueRestriction": {
            "options": [False],
            "default": False,
        },
        "minBidsNumber": {
            "options": [2],
            "default": 2,
            "minimum": 2,
            "maximum": 2,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [20],
            "default": 20,
            "minimum": 20,
            "maximum": 20,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/esco": {
        "awardComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "cancellationComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "enquiryPeriodRegulation": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "hasAuction": {
            "options": [True],
            "default": True,
        },
        "hasAwardComplaints": {
            "options": [True],
            "default": True,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [True],
            "default": True,
        },
        "hasQualificationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasTenderComplaints": {
            "options": [True],
            "default": True,
        },
        "hasValueEstimation": {
            "options": [False],
            "default": False,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [2],
            "default": 2,
            "minimum": 2,
            "maximum": 2,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [30],
            "default": 30,
            "minimum": 30,
            "maximum": 30,
        },
        "qualificationComplainDuration": {
            "options": [5],
            "default": 5,
            "minimum": 5,
            "maximum": 5,
        },
        "qualificationDuration": {
            "options": [20],
            "default": 20,
            "minimum": 20,
            "maximum": 20,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [4],
            "default": 4,
            "minimum": 4,
            "maximum": 4,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/negotiation": {
        "awardComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "cancellationComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "clarificationUntilDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "enquiryPeriodRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "hasAuction": {
            "options": [False],
            "default": False,
        },
        "hasAwardComplaints": {
            "options": [True],
            "default": True,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [False],
            "default": False,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [1],
            "default": 1,
            "minimum": 1,
            "maximum": 1,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/negotiation.quick": {
        "awardComplainDuration": {
            "options": [5],
            "default": 5,
            "minimum": 5,
            "maximum": 5,
        },
        "cancellationComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "clarificationUntilDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "enquiryPeriodRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "hasAuction": {
            "options": [False],
            "default": False,
        },
        "hasAwardComplaints": {
            "options": [True],
            "default": True,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [False],
            "default": False,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [1],
            "default": 1,
            "minimum": 1,
            "maximum": 1,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/priceQuotation": {
        "awardComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "cancellationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "clarificationUntilDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "enquiryPeriodRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "hasAuction": {
            "options": [False],
            "default": False,
        },
        "hasAwardComplaints": {
            "options": [False],
            "default": False,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [True],
            "default": True,
        },
        "hasPrequalification": {
            "options": [False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [False],
            "default": False,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [1],
            "default": 1,
            "minimum": 1,
            "maximum": 1,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [2],
            "default": 2,
            "minimum": 2,
            "maximum": 2,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restricted": {
            "options": [True, False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/reporting": {
        "awardComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "cancellationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "clarificationUntilDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "enquiryPeriodRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "hasAuction": {
            "options": [False],
            "default": False,
        },
        "hasAwardComplaints": {
            "options": [False],
            "default": False,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [False],
            "default": False,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [1],
            "default": 1,
            "minimum": 1,
            "maximum": 1,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "TenderConfig/requestForProposal": {
        "awardComplainDuration": {
            "options": [2],
            "default": 2,
            "minimum": 2,
            "maximum": 2,
        },
        "cancellationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "clarificationUntilDuration": {
            "options": [4],
            "default": 4,
            "minimum": 4,
            "maximum": 4,
        },
        "enquiryPeriodRegulation": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "hasAuction": {
            "options": [True, False],
            "default": False,
        },
        "hasAwardComplaints": {
            "options": [False],
            "default": False,
        },
        "hasAwardingOrder": {
            "options": [True, False],
            "default": False,
        },
        "hasCancellationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasEnquiries": {
            "options": [True],
            "default": True,
        },
        "hasMultiSourcing": {
            "options": [True, False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [True, False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [True, False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [False],
            "default": False,
        },
        "hasValueEstimation": {
            "options": [True, False],
            "default": False,
        },
        "hasValueRestriction": {
            "options": [True, False],
            "default": False,
        },
        "minBidsNumber": {
            "options": [1, 9],
            "default": 1,
            "minimum": 1,
            "maximum": 9,
        },
        "minEnquiriesDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "minTenderingDuration": {
            "options": [4],
            "default": 4,
            "minimum": 4,
            "maximum": 4,
        },
        "qualificationComplainDuration": {
            "options": None,
            "default": 10,
            "minimum": 0,
            "maximum": None,
        },
        "qualificationDuration": {
            "options": [20],
            "default": 20,
            "minimum": 20,
            "maximum": 20,
        },
        "restricted": {
            "options": [True, False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "valueCurrencyEquality": {
            "options": [True, False],
            "default": False,
        },
    },
    "TenderConfig/simple.defense": {
        "awardComplainDuration": {
            "options": [4],
            "default": 4,
            "minimum": 4,
            "maximum": 4,
        },
        "cancellationComplainDuration": {
            "options": [10],
            "default": 10,
            "minimum": 10,
            "maximum": 10,
        },
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "enquiryPeriodRegulation": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "hasAuction": {
            "options": [True, False],
            "default": True,
        },
        "hasAwardComplaints": {
            "options": [True],
            "default": True,
        },
        "hasAwardingOrder": {
            "options": [True],
            "default": True,
        },
        "hasCancellationComplaints": {
            "options": [True],
            "default": True,
        },
        "hasEnquiries": {
            "options": [False],
            "default": False,
        },
        "hasMultiSourcing": {
            "options": [False],
            "default": False,
        },
        "hasPreSelectionAgreement": {
            "options": [False],
            "default": False,
        },
        "hasPrequalification": {
            "options": [False],
            "default": False,
        },
        "hasQualificationComplaints": {
            "options": [False],
            "default": False,
        },
        "hasTenderComplaints": {
            "options": [True],
            "default": True,
        },
        "hasValueEstimation": {
            "options": [True],
            "default": True,
        },
        "hasValueRestriction": {
            "options": [True],
            "default": True,
        },
        "minBidsNumber": {
            "options": [1],
            "default": 1,
            "minimum": 1,
            "maximum": 1,
        },
        "minEnquiriesDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "minTenderingDuration": {
            "options": [6],
            "default": 6,
            "minimum": 6,
            "maximum": 6,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "qualificationDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restricted": {
            "options": [False],
            "default": False,
        },
        "tenderComplainRegulation": {
            "options": [2],
            "default": 2,
            "minimum": 2,
            "maximum": 2,
        },
        "valueCurrencyEquality": {
            "options": [True],
            "default": True,
        },
    },
    "FrameworkConfig/dynamicPurchasingSystem": {
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "hasItems": {
            "options": [True, False],
            "default": False,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restrictedDerivatives": {
            "options": [True, False],
            "default": False,
        },
    },
    "FrameworkConfig/electronicCatalogue": {
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "hasItems": {
            "options": [False],
            "default": False,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restrictedDerivatives": {
            "options": [False],
            "default": False,
        },
    },
    "FrameworkConfig/internationalFinancialInstitutions": {
        "clarificationUntilDuration": {
            "options": [3],
            "default": 3,
            "minimum": 3,
            "maximum": 3,
        },
        "hasItems": {
            "options": [True, False],
            "default": False,
        },
        "qualificationComplainDuration": {
            "options": [0],
            "default": 0,
            "minimum": 0,
            "maximum": 0,
        },
        "restrictedDerivatives": {
            "options": [True, False],
            "default": False,
        },
    },
}
