"""
Regenerate ``criteria_templates.py`` from the bundled criteria catalogue.

    python robot_tests/libraries/data/generate_criteria_templates.py

The bundled ``aboveThreshold`` data folder holds the criteria the CDB expects,
with their Ukrainian titles, descriptions and legislation. This script lifts
them into a Python module keyed by classification id, dropping the generated
requirement ids and the lot binding, which ``criteria.criterion()`` assigns
when it builds a criterion.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

SOURCE = Path("procedure_tools/data/aboveThreshold/2014_tender_criteria_post.json")
TARGET = Path("robot_tests/libraries/data/criteria_templates.py")

# Assigned per build, never carried over from the catalogue.
DROPPED_KEYS = ("id", "relatedItem")

HEADER = '''"""
Criterion templates, keyed by classification id.

The shapes come from the criteria catalogue the CDB expects for a Ukrainian
above threshold procedure: titles, descriptions, legislation, requirement
groups and their eligible evidences. Requirement ids and the lot binding are
left out on purpose, ``criteria.criterion()`` assigns them on every build.

Generated by ``generate_criteria_templates.py``; put changes in ``criteria.py``
so a regeneration does not drop them.
"""

from typing import Any

TEMPLATES: dict[str, dict[str, Any]] = '''


def strip(node: Any) -> Any:
    if isinstance(node, dict):
        return {key: strip(value) for key, value in node.items() if key not in DROPPED_KEYS}
    if isinstance(node, list):
        return [strip(item) for item in node]
    return node


def build_templates(criteria: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    templates: dict[str, dict[str, Any]] = {}
    for criterion in criteria:
        classification_id = criterion["classification"]["id"]
        cleaned = strip(criterion)
        if classification_id in templates:
            if templates[classification_id] != cleaned:
                raise ValueError(f"{classification_id}: the catalogue has two different shapes for it")
            continue
        templates[classification_id] = cleaned
    return templates


def literal(value: Any) -> str:
    """A scalar as source, double quoted like the rest of the code base."""
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    return repr(value)


def render(node: Any, indent: int = 0) -> str:
    """Python literal for ``node``, one entry per line, so diffs stay readable."""
    pad = "    " * indent
    inner = "    " * (indent + 1)
    if isinstance(node, dict):
        if not node:
            return "{}"
        entries = "".join(
            f"{inner}{literal(key)}: {render(value, indent + 1)},\n" for key, value in sorted(node.items())
        )
        return "{\n" + entries + pad + "}"
    if isinstance(node, list):
        if not node:
            return "[]"
        entries = "".join(f"{inner}{render(item, indent + 1)},\n" for item in node)
        return "[\n" + entries + pad + "]"
    return literal(node)


def main() -> None:
    criteria = json.loads(SOURCE.read_text(encoding="utf-8"))["data"]
    templates = build_templates(criteria)
    TARGET.write_text(HEADER + render(templates) + "\n", encoding="utf-8")
    print(f"{TARGET}: {len(templates)} criterion templates")


if __name__ == "__main__":
    main()
