"""
Regenerate ``config_schemas.py`` from the standards library.

    python robot_tests/libraries/data/generate_config_schemas.py [path/to/standards]

Config is how the CDB branches, and what a procedure may set is decided by the
JSON schemas in the standards library rather than by the API code. Most keys
are pinned to a single value per procedure; only some are free to vary, and the
same key can be free in one procedure and pinned in another, with a different
default. That is the whole config test space, so it is lifted here instead of
being guessed.

The snapshot is tied to the standards checkout it came from - a different
branch or tag can pin different values - so regenerate it against the version
the environment under test runs.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

DEFAULT_STANDARDS = Path(__file__).resolve().parents[4] / "standards"
TARGET = Path("robot_tests/libraries/data/config_schemas.py")
GROUPS = ("TenderConfig", "FrameworkConfig")

HEADER = '''"""
What each procedure may put in its config, by procedure and key.

``options`` is what the key may be set to and ``default`` is what it is without
being set. A key with one option is pinned by the schema: the API refuses any
other value, so the only thing to test about it is that refusal. A key with
several is a real branch of behaviour, and the same key can be pinned in one
procedure and free in another.

Generated by ``generate_config_schemas.py`` from the standards library
{provenance}. Regenerate it against the standards version the environment under
test runs; a different branch can pin different values.
"""

from typing import Any

SCHEMAS: dict[str, dict[str, dict[str, Any]]] = '''


def describe(spec: dict[str, Any]) -> dict[str, Any]:
    """What a key may hold, as options plus the value it takes by default."""
    default = spec.get("default")
    if "enum" in spec:
        return {"options": list(spec["enum"]), "default": default}
    low, high = spec.get("minimum"), spec.get("maximum")
    if low is None or high is None:
        return {"options": None, "default": default, "minimum": low, "maximum": high}
    options = [low] if low == high else [low, high]
    return {"options": options, "default": default, "minimum": low, "maximum": high}


def render(node: Any, indent: int = 0) -> str:
    pad, inner = "    " * indent, "    " * (indent + 1)
    if isinstance(node, dict):
        if not node:
            return "{}"
        body = "".join(f"{inner}{key!r}: {render(value, indent + 1)},\n" for key, value in node.items())
        return "{\n" + body + pad + "}"
    if isinstance(node, list):
        return "[" + ", ".join(render(item) for item in node) + "]"
    return repr(node)


def provenance(standards: Path) -> str:
    try:
        revision = subprocess.run(
            ["git", "-C", str(standards), "describe", "--always", "--dirty"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        return f"at {revision}"
    except (subprocess.CalledProcessError, OSError):
        return "(revision unknown)"


def main() -> None:
    standards = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_STANDARDS
    schema_dir = standards / "data_model" / "schema"
    if not schema_dir.is_dir():
        raise SystemExit(f"no schemas under {schema_dir}; pass the path to a standards checkout")
    schemas: dict[str, dict[str, dict[str, Any]]] = {}
    for group in GROUPS:
        for path in sorted((schema_dir / group).glob("*.json")):
            properties = json.loads(path.read_text(encoding="utf-8")).get("properties", {})
            schemas[f"{group}/{path.stem}"] = {key: describe(spec) for key, spec in sorted(properties.items())}
    header = HEADER.format(provenance=provenance(standards))
    TARGET.write_text(header + render(schemas) + "\n", encoding="utf-8")
    variable = sum(1 for keys in schemas.values() for entry in keys.values() if len(entry["options"] or []) > 1)
    print(f"{TARGET}: {len(schemas)} procedures, {variable} keys that can vary")


if __name__ == "__main__":
    main()
