"""
Regenerate ``criteria_templates.py`` from the bundled criteria catalogue.

    python robot_tests/libraries/data/generate_criteria_templates.py

Every bundled data folder that posts criteria holds the shapes the CDB expects,
with their Ukrainian titles, descriptions and legislation. This script lifts
them all into a Python module keyed by classification id, dropping the ids that
are generated and the binding to a lot or an item, which
``criteria.criterion()`` assigns when it builds a criterion. Scanning every
folder is what keeps the catalogue complete: the localisation criterion, for
one, appears only in the ``.local`` folders.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

DATA = Path("procedure_tools/data")
TARGET = Path("robot_tests/libraries/data/criteria_templates.py")

# Assigned per build, never carried over from the catalogue. Only the ids the
# client generates are dropped: the ones on the requirement groups and the
# requirements, and the lot or item a criterion is bound to. The ids that are
# part of the content - the law a legislation entry points at, the
# classification - are kept.
DROPPED_CRITERION_KEYS = ("id", "relatedItem")
DROPPED_GROUP_KEYS = ("id",)
DROPPED_REQUIREMENT_KEYS = ("id",)

HEADER = '''"""
Criterion templates, keyed by classification id, and which folder posts which.

The shapes come from the criteria catalogue the CDB expects for a Ukrainian
above threshold procedure: titles, descriptions, legislation, requirement
groups and their eligible evidences. Requirement ids and the lot binding are
left out on purpose, ``criteria.criterion()`` assigns them on every build.

``FOLDERS`` says which criteria each data folder posts, in the order it posts
them, so a suite that mirrors a folder asks for exactly that set. A criterion
valid only in one procedure - the life cycle cost ones, for instance - is in
``TEMPLATES`` but only in the folders that may use it.

Generated by ``generate_criteria_templates.py``; put changes in ``criteria.py``
so a regeneration does not drop them.
"""

from typing import Any

TEMPLATES: dict[str, dict[str, Any]] = '''


def strip(criterion: dict[str, Any]) -> dict[str, Any]:
    """The criterion without the ids that are generated when it is built."""
    data = {key: value for key, value in criterion.items() if key not in DROPPED_CRITERION_KEYS}
    data["requirementGroups"] = [
        {
            **{key: value for key, value in group.items() if key not in DROPPED_GROUP_KEYS},
            "requirements": [
                {key: value for key, value in requirement.items() if key not in DROPPED_REQUIREMENT_KEYS}
                for requirement in group.get("requirements", [])
            ],
        }
        for group in criterion.get("requirementGroups", [])
    ]
    return data


def build_templates(criteria: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    templates: dict[str, dict[str, Any]] = {}
    for criterion in criteria:
        classification_id = criterion["classification"]["id"]
        cleaned = strip(criterion)
        if classification_id in templates:
            # the same criterion appears in many folders; the first shape wins
            continue
        templates[classification_id] = cleaned
    return templates


def literal(value: Any) -> str:
    """A scalar as source, double quoted like the rest of the code base."""
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    return repr(value)


def render(node: Any, indent: int = 0) -> str:
    """Python literal for ``node``, one entry per line, so diffs stay readable."""
    pad = "    " * indent
    inner = "    " * (indent + 1)
    if isinstance(node, dict):
        if not node:
            return "{}"
        entries = "".join(
            f"{inner}{literal(key)}: {render(value, indent + 1)},\n" for key, value in sorted(node.items())
        )
        return "{\n" + entries + pad + "}"
    if isinstance(node, list):
        if not node:
            return "[]"
        entries = "".join(f"{inner}{render(item, indent + 1)},\n" for item in node)
        return "[\n" + entries + pad + "]"
    return literal(node)


def collect() -> tuple[list[dict[str, Any]], dict[str, list[str]]]:
    """Every criterion any bundled data folder posts, and which folder posts what."""
    criteria: list[dict[str, Any]] = []
    folders: dict[str, list[str]] = {}
    for path in sorted(DATA.glob("*/*tender_criteria_post*.json")):
        posted = json.loads(path.read_text(encoding="utf-8"))["data"]
        criteria.extend(posted)
        folders[path.parent.name] = [item["classification"]["id"] for item in posted]
    return criteria, folders


def main() -> None:
    criteria, folders = collect()
    templates = build_templates(criteria)
    body = render(templates) + "\n\nFOLDERS: dict[str, list[str]] = " + render(folders) + "\n"
    TARGET.write_text(HEADER + body, encoding="utf-8")
    print(f"{TARGET}: {len(templates)} criteria across {len(folders)} folders")


if __name__ == "__main__":
    main()
