name: Fast Test Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  pytest:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ['2.x', '3.x']
        case:
          - reporting
          - negotiation
          - negotiation_quick
          - below_threshold
          - below_threshold_multilot
          - above_threshold_eu
          - above_threshold_eu_multilot
          - above_threshold_eu_plan
          - above_threshold_eu_tender
          - above_threshold_ua
          - above_threshold_ua_defense
          - close_framework_agreement_ua
          - close_framework_agreement_ua_central
          - competitive_dialogue_eu
          - competitive_dialogue_ua
          - esco
          - esco_features
          - esco_multilot
    env:
      PYTHONUNBUFFERED: 1
    steps:
      - uses: actions/checkout@v2
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Kiev
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Run pytest
        env:
          FAST_RUN: 1
          API_HOST: ${{ secrets.API_HOST }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          DS_HOST: ${{ secrets.DS_HOST }}
          DS_USERNAME: ${{ secrets.DS_USERNAME }}
          DS_PASSWORD: ${{ secrets.DS_PASSWORD }}
        run: |
          pytest procedure_tools/test.py::test_${{ matrix.case }}
