name: Fast Test Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Run black
        run: |
          black . --check
  pytest-fast:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        case:
          - above_threshold
          - above_threshold_features
          - above_threshold_lcc
          - above_threshold_eu
          - above_threshold_eu_features
          - above_threshold_eu_lcc
          - above_threshold_ua
          - above_threshold_ua_features
          - above_threshold_ua_lcc
          - below_threshold
          - below_threshold_central
          - below_threshold_features
          - close_framework_agreement_ua
          - close_framework_agreement_ua_central
          - competitive_dialogue_eu
          - competitive_dialogue_ua
          - competitive_dialogue_ua_features
          - esco
          - esco_features
          - negotiation
          - negotiation_quick
          - reporting
          - simple_defense
          - dynamic_purchasing_system_competitive_ordering
          - dynamic_purchasing_system_price_quotation
          - request_for_proposal
          - international_financial_institutions_request_for_proposal
    env:
      PYTHONUNBUFFERED: 1
    steps:
      - uses: actions/checkout@v4
      - name: Setup timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: Europe/Kiev
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Run pytest
        env:
          FAST_RUN: 1
          API_HOST: ${{ secrets.API_HOST }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          DS_HOST: ${{ secrets.DS_HOST }}
          DS_USERNAME: ${{ secrets.DS_USERNAME }}
          DS_PASSWORD: ${{ secrets.DS_PASSWORD }}
        run: |
          pytest procedure_tools/test.py::test_${{ matrix.case }}
