name: Full Test Workflow

on: [workflow_dispatch]

jobs:
  pytest-full:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        case:
          - above_threshold
          - above_threshold_features
          - above_threshold_lcc
          - above_threshold_eu
          - above_threshold_eu_features
          - above_threshold_eu_lcc
          - above_threshold_ua
          - above_threshold_ua_features
          - above_threshold_ua_lcc
          - below_threshold
          - below_threshold_central
          - below_threshold_features
          - close_framework_agreement_ua
          - close_framework_agreement_ua_central
          - competitive_dialogue_eu
          - competitive_dialogue_ua
          - competitive_dialogue_ua_features
          - esco
          - esco_features
          - negotiation
          - negotiation_quick
          - reporting
          - simple_defense
    env:
      PYTHONUNBUFFERED: 1
    steps:
      - uses: actions/checkout@v4
      - name: Setup timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: Europe/Kiev
      - name: Set up python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Run pytest
        env:
          API_HOST: ${{ secrets.API_HOST }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          DS_HOST: ${{ secrets.DS_HOST }}
          DS_USERNAME: ${{ secrets.DS_USERNAME }}
          DS_PASSWORD: ${{ secrets.DS_PASSWORD }}
        run: |
          pytest procedure_tools/test.py::test_${{ matrix.case }}
