name: Case Test Workflow

on:
  workflow_dispatch:
    inputs:
      case:
        description: 'Test Case'
        required: false
jobs:
  pytest-case:
    if: github.event.inputs.case != ''
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: 1
    steps:
      - uses: actions/checkout@v4
      - name: Setup timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: Europe/Kiev
      - name: Set up python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Run pytest
        env:
          API_HOST: ${{ secrets.API_HOST }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          DS_HOST: ${{ secrets.DS_HOST }}
          DS_USERNAME: ${{ secrets.DS_USERNAME }}
          DS_PASSWORD: ${{ secrets.DS_PASSWORD }}
        run: |
          pytest procedure_tools/test.py::test_${{ github.event.inputs.case }}
