name: Full Test Workflow

on:
  workflow_dispatch:
    inputs:
      case:
        description: 'Test Case Name'

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: ['2.x', '3.x']
        test-case:
          - test_reporting
          - test_negotiation
          - test_negotiation_quick
          - test_below_threshold
          - test_below_threshold_multilot
          - test_above_threshold_eu
          - test_above_threshold_eu_multilot
          - test_above_threshold_eu_plan
          - test_above_threshold_eu_tender
          - test_above_threshold_ua
          - test_above_threshold_ua_defense
          - test_close_framework_agreement_ua
          - test_close_framework_agreement_ua_central
          - test_competitive_dialogue_eu
          - test_competitive_dialogue_ua
          - test_esco
          - test_esco_features
          - test_esco_multilot
    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Run pytest
        env:
          API_HOST: ${{ secrets.API_HOST }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          DS_HOST: ${{ secrets.DS_HOST }}
          DS_USERNAME: ${{ secrets.DS_USERNAME }}
          DS_PASSWORD: ${{ secrets.DS_PASSWORD }}
        run: |
          pytest procedure_tools/test.py::${{ matrix.test-case }}
